# Generated by Django 5.0.3 on 2024-03-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('title', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=1000)),
                ('exampleTestcases', models.TextField(default='')),
                ('expectedOutputType', models.CharField(max_length=50)),
            ],
        ),
    ]
